Resolution to GB Authentication issue
Sholofly/lghorizon-python pull request #43
Opened 2024-10-09 20:53 UTC by ColinRobbins

The library element of a PR to resolve the issue that the GB integration was no longer working...

https://github.com/Sholofly/lghorizon/issues/82

Changes:
- replaced `authorise_gb` with new code.   
- reverted GB MQTT token to default - GB specific code generated errors.

The authorise_gb code uses a supplied refresh_token, rather than username/password to login.
Not as convenient for the user, but avoids the challenge of emulating the GB OAUTH process.

2024-10-09 20:53 UTC, ColinRobbins commented
Accompanying pull to the HA component in a few days...

2024-10-10 14:41 UTC, Sholofly requested changes
LGTM. Thank you! One additional request. Could you add a detailed description in the readme how to obtain the refresh token?

2024-10-11 08:45 UTC, ColinRobbins commented
@Sholofly I've added the configuration details in the Readme of the HA plugin

2024-10-11 21:02 UTC, Sholofly approved these changes

2024-10-11 21:04 UTC, merged